python inference.py \
--output_dir ./models/train_dataset \
--fp16 \
--overwrite_output_dir \
--train_data ./data/emotion_all_20_train.csv \
--eval_data ./data/emotion_all_20_eval.csv \
--model_name_or_path ./models/train_dataset \
--per_device_train_batch_size 32 \
--per_device_eval_batch_size 32 \
--gradient_accumulation_steps 4 \
--num_train_epochs 5 \
--weight_decay 0.01 \
--warmup_ratio 0.1 \
--learning_rate 2e-5 \
--eval_steps 100 \
--logging_steps 100 \
--save_steps=1000 \
--load_best_model_at_end \
--evaluation_strategy steps \