python train.py \
--output_dir ./models/total_comment_emotion \
--fp16 \
--overwrite_output_dir \
--train_data ./dataset/diary_train.csv \
--eval_data ./dataset/diary_test.csv \
--model_name_or_path gogamza/kobart-base-v2 \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 128 \
--num_train_epochs 5 \
--weight_decay 0.01 \
--warmup_ratio 0.1 \
--learning_rate 5.6e-5 \
--eval_steps 1000 \
--logging_steps 100 \
--save_steps=1000 \
--save_total_limit=3 \
--predict_with_generate=True \
--temperature 0.7 \
--min_target_length 30 \
--max_seq_length 512 \
--max_target_length 128 \
--load_best_model_at_end \
--evaluation_strategy steps \
--wandb_entity sajo-tuna \
--wandb_project generation_test \
--wandb_name generation_test